### ISSUE TITLE
[BUG] *Sparse matrix error when calculating the transformer 63/10*

### ISSUE THREAD

**Issue by WinApiMan** [PowerGridModel/power-grid-model#1162]
**Hi!I encountered a problem. When calculating the asymmetrical short circuit (A) on the 0.4 kV busbar of a transformer with Id=1503, a sparse matrix error occurs.Moreover, when calculating an asymmetrical short circuit on the buses of a similar transformer ID=1426, such an error does not occur. We reconnected the objects. We replaced ID=1426 with ID=1503, and set 1426 instead of 1503. However, the error still occurs precisely where ID=1503 is set. Perhaps this isn't a bug, but my own mistake, and you can help me solve this problem.**

**Input Data Validity**
[calculate_model 1503.json](https://github.com/user-attachments/files/23022103/calculate_model.1503.json)

[calculate_model ID1426.json](https://github.com/user-attachments/files/23022104/calculate_model.ID1426.json)

[calculate_output_model ID1426.json](https://github.com/user-attachments/files/23022114/calculate_output_model.ID1426.json)

**Screenshots**

<img width="700" height="218" alt="Image" src="https://github.com/user-attachments/assets/285882f7-4aea-4236-a1ac-be64d123a8a6" />

**Comment by mgovers** [comment]
hi @WinApiMan, Thank you for reporting this. 

Can you try to load the data into Python and use the data validator (https://power-grid-model.readthedocs.io/en/stable/user_manual/data-validator.html)? This may expose some basic usage problems that may not be caught in the C API.

Can you please also provide the exact PGM version you are running (either release tag or Git SHA) and, ideally, an example script of how you run the PGM? With that, we can try to have a look at this tomorrow.

**Comment by mgovers** [comment]
FYI, I've been able to reproduce the `SparseMatrixError` and I also confirmed that our data validator does not signify any errors. We will dive into this now.

**Comment by WinApiMan** [comment]
Hi @mgovers, Thanks for the quick reply.

We are using version 1.12.54. I'm attaching a test example of the call script and errors.

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/cbb3a622-1476-4dfc-bb02-d6aa3c706544" />

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/0f346fb6-7855-4eec-a0ee-ce283909252e" />

**Comment by mgovers** [comment]
Thank you for your extensive input, it really helps with the investigation. This indeed seems something that requires a deep-dive on our end. We will investigate.

**Comment by figueroa1395** [comment]
Hello @WinApiMan, 

I want to let you know that we are actively working on this issue. We have found some leads, but nothing conclusive yet. We will communicate with you as soon as we have more concrete progress.

**Comment by WinApiMan** [comment]
Hi @figueroa1395!Thank you, the moment is quite relevant, so we are waiting

**Comment by WinApiMan** [comment]
@mgovers, @figueroa1395 , Hi!We ran a series of further tests and found a pattern. If after transformer (after to_node) we have only one node, we get sparse matrix error. However, when we added another node after to_node  and connected it to the to_node, model was calculated.  Maybe this will help you.

[calculate_model_test_2041_invalid.json](https://github.com/user-attachments/files/23337009/calculate_model_test_2041_invalid.json)

[calculate_model_test_2041_valid.json](https://github.com/user-attachments/files/23337010/calculate_model_test_2041_valid.json)

**Comment by petersalemink95** [comment]
Hi @WinApiMan,

Thanks for thinking along!
The problem is probably caused because:
- The solvers used in PGM solve in the phase (abc) domain. We also use these solvers to solve short circuit calculations
- In this particular case the grid is floating: no `Dn` or `Yn` connection + no shunt and the fault is 2 phase. In the phase domain this results in a sparse matrix error. 
- However, for short circuit calculations, this particular case is solvable in the sequence domain (012)

We might have wrongfully assumed that we can solve all short circuit calculations in the phase domain. If this is the case the solution will not be trivial, unfortunately.

**Comment by WinApiMan** [comment]
@mgovers , @petersalemink95, I don't think the problem lies in the asymmetrical short circuit calculation. Here's an example of the same error in the Power Flow and asymmetrical load calculation.

[calculate_model PF invalid.json](https://github.com/user-attachments/files/23354183/calculate_model.PF.invalid.json)

**Comment by WinApiMan** [comment]
For analysis, we added an additional link after the transformer and before the load to the previous scheme. The scheme began processing and at the 30th iteration, showed a numericla error of 0.02, but then numerical error began to increase and a sparse matrix error occurred.

[calculate_model PF invalid_2232.json](https://github.com/user-attachments/files/23355551/calculate_model.PF.invalid_2232.json)

**Comment by petersalemink95** [comment]
Hi @WinApiMan,

You are right that a similar thing does happen in power flow calculations. Reason: we cannot do calculations in the phase domain on floating grids. However, there is a difference:
- for power flow calculations this is expected
- for short circuit calculations we should be able to calculate the short circuit current using the sequence domain

There are some potential resolutions that we're looking in to:
- re-writing the solvers of short circuit calculations to the sequence domain - this would be a lot of work and is not going to be a "quick fix"
- Internally adding a large grounding impedance to the transformer - this can be easier to implement and might (to be investigated) also provide a solution in the power flow case

**Comment by petersalemink95** [comment]
Hi @WinApiMan,

Update from our side: we're investigating the 2nd option I mentioned above - "Internally adding a large grounding impedance to the transformer". Currently we see promising results. We're adding more validation cases to prove that this is the right direction forward. If this is indeed the case we're expecting to have the full implementation available within 2 weeks.

**Comment by WinApiMan** [comment]
@petersalemink95  , Great, I hope you're right :)

**Comment by WinApiMan** [comment]
@TonyXiang8787, @mgovers . We used the last pgm version 1.12.69. The sparse matrix error didn't disappear.

Files

[calculate_model_1.json](https://github.com/user-attachments/files/23647264/calculate_model_1.json)

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/674c17cf-2572-43e8-a303-1c50fbe528b6" />

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/f32b5242-bf2a-48b8-9098-1a35e539d197" />

Additional test

[calculate_model.json](https://github.com/user-attachments/files/23647573/calculate_model.json)

**Comment by mgovers** [comment]
@WinApiMan ~Awesome, that's great to hear!~ EDIT: I mis-read. That's unfortunate. See below for continuation.

Thank you for your patience. It took us some time to come up with a good and stable solution (in particular, one that doesn't potentially break other things).

We will be working on some documentation additions in the near future regarding our findings, as well as some other, closely related improvements

**Comment by mgovers** [comment]
> [@TonyXiang8787](https://github.com/TonyXiang8787), [@mgovers](https://github.com/mgovers) . We used the last pgm version 1.12.69. The sparse matrix error didn't disappear.
> 
> Files
> 
> [calculate_model_1.json](https://github.com/user-attachments/files/23647264/calculate_model_1.json)
> <img alt="Image" width="1440" height="900" src="https://private-user-images.githubusercontent.com/61493290/516683455-674c17cf-2572-43e8-a303-1c50fbe528b6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2MjQxNjksIm5iZiI6MTc2MzYyMzg2OSwicGF0aCI6Ii82MTQ5MzI5MC81MTY2ODM0NTUtNjc0YzE3Y2YtMjU3Mi00M2U4LWEzMDMtMWM1MGZiZTUyOGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIwVDA3MzEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZmY0OWVlYTYwNDE5NTU4OWQ0ZDUwNTNlODNlZmE0YTgxODIzNmZmZGYzYWM0NjVkZmE2ZjZiYzhkMTkxNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gzTaS61pi68Tv4MTkd8hU8W9Fb3Dv0ofEFgP4EUmkds"> <img alt="Image" width="1440" height="900" src="https://private-user-images.githubusercontent.com/61493290/516683542-f32b5242-bf2a-48b8-9098-1a35e539d197.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2MjQxNjksIm5iZiI6MTc2MzYyMzg2OSwicGF0aCI6Ii82MTQ5MzI5MC81MTY2ODM1NDItZjMyYjUyNDItYmYyYS00OGI4LTkwOTgtMWEzNWU1MzlkMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIwVDA3MzEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YjI2MjM4N2VjMzZkODFlYmY3NTg1YTA5ZjZjOTM4YWUzZjg2OWM5ZTM0YjI5MTBhNGI0YTNjMDM1ODZiY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0LyNffhY-gbn_jIRgJBma4rQUAfTfhQko0NNYX2HZtQ">
> 
> Additional test
> 
> [calculate_model.json](https://github.com/user-attachments/files/23647573/calculate_model.json)


> [@WinApiMan](https://github.com/WinApiMan) Awesome, that's great to hear!
> 
> Thank you for your patience. It took us some time to come up with a good and stable solution (in particular, one that doesn't potentially break other things).
> 
> We will be working on some documentation additions in the near future regarding our findings, as well as some other, closely related improvements

I apologize, I misread. you said it **didn't disappear**. That's a shame. I'll do a quick investigation.

**Comment by mgovers** [comment]
If i reduce the `max_iterations` significantly, I do get another indication of what is happening: `IterationDiverge`. That points towards calculation instabilities. Setting `max_iterations` very high may lead to various types of behavior (limit cycles, divergences, ...) and therefore, the state can at some point not be trusted anymore. The real issue is the fact that the calculation does not converge.

I am still trying to investigate the underlying issue, but seems to be a different problem from the one that this issue is about. If that is indeed the case, maybe we need to close the issue and re-open a new one.

**Comment by WinApiMan** [comment]
@mgovers For analysis, we tried increasing the error_tolerance value, and at a value of 1e-1, an error appeared that we didn't understand

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/7eee689f-99c2-44ac-8c94-21738647f85d" />

**Comment by mgovers** [comment]
> [@mgovers](https://github.com/mgovers) For analysis, we tried increasing the error_tolerance value, and at a value of 1e-1, an error appeared that we didn't understand
> <img alt="Image" width="1440" height="900" src="https://private-user-images.githubusercontent.com/61493290/516733112-7eee689f-99c2-44ac-8c94-21738647f85d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2Mjg2NDIsIm5iZiI6MTc2MzYyODM0MiwicGF0aCI6Ii82MTQ5MzI5MC81MTY3MzMxMTItN2VlZTY4OWYtOTljMi00NGFjLThjOTQtMjE3Mzg2NDdmODVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIwVDA4NDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMGMzZjMyNjY2ODg0OTRiYWRmMGI0NzU4ZmY4NWNmYWI1NTY0ODljMzEwM2ZlMjZiZmQ2YWUzZjdlMTE4OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qxgTYvvGGYvB10iHDKrPlgGH5iNTNKxs4AQXvBu2qBo">

I think by that point, you're running into really weird edge cases (undefined behavior; see also https://power-grid-model.readthedocs.io/en/stable/advanced_documentation/terminology.html#undefined-behavior). Usually, that means that you've entered the wrong rabbit hole 😬 Instead, our recommendation is to try to come up with a smaller, simpler version of the grid that reproduces the same behavior (a minimal reproducible case). That's much simpler to reason about, and often is able to pinpoint the exact problem you're running into.

On that note, in the meantime, I've managed to reproduce the issue with a single source, transformer, sym load and asym load. For simplicity, I've also rounded some values to nearest power of 10, as well as remapped the IDs.

```json
{
  "version": "1.0",
  "type": "input",
  "is_batch": false,
  "attributes": {},
  "data": {
    "node": [
      {"id": 0, "u_rated": 10000},
      {"id": 1, "u_rated": 1000}
    ],
    "transformer": [
      {"id": 2, "from_node": 0, "to_node": 1, "from_status": 1, "to_status": 1, "u1": 10000, "u2": 1000, "sn": 100000, "uk": 0.10000000000000001, "pk": 1000, "i0": 0.01, "p0": 100, "winding_from": 0, "winding_to": 1, "clock": 0, "tap_side": 0, "tap_pos": 3, "tap_min": 1, "tap_max": 5, "tap_nom": 3, "tap_size": 100, "uk_min": 0.10000000000000001, "uk_max": 0.10000000000000001, "pk_min": 1000, "pk_max": 1000, "r_grounding_from": 0, "x_grounding_from": 0, "r_grounding_to": 0, "x_grounding_to": 0}
    ],
    "source": [
      {"id": 3, "node": 0, "status": 1, "u_ref": 1, "u_ref_angle": 0, "sk": 100000000, "rx_ratio": 1, "z01_ratio": 1000000}
    ],
    "sym_load": [
      {"id": 4, "node": 0, "status": 1, "type": 0, "p_specified": 100000, "q_specified": 100000}
    ],
    "asym_load": [
      {"id": 5, "node": 1, "status": 1, "type": 0, "p_specified": [50000, 40000, 30000], "q_specified": [20000, 10000, 0]}
    ]
  }
}
```

At this point, this feels very closely related to another, related but definitely separate thing we're looking into separately, which is the sparse matrix solving stability (see e.g. #1125 and #1167). We're re-iterating on that because the original direction didn't seem to be the right one, so it's still work in progress. However, I can't be sure at this point and will have to take this back to the team first.

**Comment by WinApiMan** [comment]
@mgovers  Thanks for the information. We use parts of a real network for testing, so this was the smallest part that we were able to generate quickly :)

**Comment by mgovers** [comment]
We've had some extensive discussions within the team and we found a couple things.

1. There is at least one data error:
   1. `z01_ratio` should be of the order of magnitude of `1`, not `1e6` (this seems to be a data error)
   2. `sk`, we expect to be of the order of magnitude of `1e12`, not `1e7 ~ 1e8` (we expect this to be data error but we can't be sure)
2. If these are solved, the underlying source of the iteration diverge changes from the transformers to the links:
   1. Links are known to cause calculation instabilities. This is related to the work in #1125 and #1167. Hopefully that will reduce the amount of edge cases we encounter in the mid- to long-term, but that will not provide a guaranteed workaround.
   2. As a workaround, you can try to replace the links with low-impedance lines, e.g. `r1=1e-6, x1=1e-6, c1=0, tan1=0, r0=1e-6, x0=1e-6, c0=0, tan0=0`. This seems to resolve the case you sent me.
3. There are some other things that popped up in the discussion that we are going to take offline, but they probably do not affect you directly.

Can you please see if these things resolve the problems you are encountering?

**Comment by WinApiMan** [comment]
We can certainly change this. But this is an artificial parameter change. We're using real network parameters: Un = 10,000 V, Isc = 5,000 A. If we use 10e12, the current would need to be increased by a factor of 10,000, and I've never encountered such currents in distribution networks in my entire career. Using the z0 coefficient in the source, we simulate a network with an isolated neutral; setting z0 = 1 would result in a network with a grounded neutral, and problems 1000%) would not arise. We're interested in the library's behavior specifically in such weak and isolated networks. If you need it for your research, we can conduct an experiment with your parameters, but it will be far from realistic.

**Comment by WinApiMan** [comment]
Unfortunately, we can't quickly replace all the links on the line (the object generation algorithm needs to be changed), but we reduced their number and removed the direct connection between the load and the source. And this truly produced a workable model on this small portion of the network.

**Comment by mgovers** [comment]
@TonyXiang8787, @petersalemink95 or @nitbharambe, can one of you guys please give some input here as power system experts with electrical engineering background?

**Comment by TonyXiang8787** [comment]
Hi @WinApiMan,

The main problem of the network is your specified transformer configuration. You now have a `Yyn` transformer, which does not allow significant zero sequence current flow in the secondary side. And there are asymmetrical loads connecting at the secondary side.

I would not image such a configuration exists in the reality. Most likely, I guess the actual transformer configration is `YynD`, a three-winding transformer with an internal delta-winding which has no connection to the outside. Maybe you can have a check on the specsheet of the transformer or your database?

**Comment by WinApiMan** [comment]
@TonyXiang8787 , @mgovers , We are sending you the diagrams of two substations from the provided model. Current imbalance in the 0.4 kV network is entirely possible. It may not be as severe as shown in the model, but the values ​​are close to reality.

<img width="406" height="656" alt="Image" src="https://github.com/user-attachments/assets/8a5bf5e5-246d-4725-8390-dcffb7679060" />

<img width="402" height="639" alt="Image" src="https://github.com/user-attachments/assets/b55d7896-b06b-4978-9116-7cbcc0ffe992" />

**Comment by TonyXiang8787** [comment]
Hi @WinApiMan,

Thanks for sharing the diagram. The diagram is makng sense. However, it still does not show if the transformer has an internal delta winding or not. It is usually not shown in the schematics. Maybe you need to check the actual specsheet of the transformer?

**Comment by WinApiMan** [comment]
@TonyXiang8787 We simulate a real section 10 kV network with loads from the 0.4 kV side. We also have transformers with Y/Yn windings.

Power transformer example:

https://thetimesenergygroup.uz/en/products/power-oil-transformer-tmg-100610-04.htm

<img width="1941" height="1354" alt="Image" src="https://github.com/user-attachments/assets/e3dae532-d8fc-4475-bd04-d1811642bbc4" />

**Comment by TonyXiang8787** [comment]
Hi @WinApiMan,

Thanks for sharing the information and your patience. I have done more in-depth investigation and found we indeed have another design fault in the zero-sequence modelling of transformer, espacially for `Yyn` transformers. I have tried a quick fix and it works in your network with `error_tolerence=1e-4` and default maximum iteration steps.

However, it would take more time to actually adjust all the test and add new test to release the fix. So it will take a while to release. If you want to also test this beta version yourself, we can build a wheel for you to test. Please indicate which operating system (and CPU architecture) you are using.

**Comment by WinApiMan** [comment]
Hi @TonyXiang8787 Thanks for the quick reply! We use Windows x64 and we use your library for C++ (power_grid_model_c.dll). If you provide us with a test version for testing, we will be happy to test it and share the results.

**Comment by TonyXiang8787** [comment]
@WinApiMan, Ah you are using C++, I guess you compile the library from source? You can try to checkout the branch in #1197 and re-compile the library.

**Comment by WinApiMan** [comment]
@TonyXiang8787  Yes, you are absolutely right, we compile on our side. We will try to test it and write you the results.

**Comment by WinApiMan** [comment]
@TonyXiang8787  The new version calculated a small network that the old version couldn't. But when connecting a large number of nodes and transformers, a sparse matrix error occurred again. For analysis, we were able to connect 166 transformers to the source at idle. But the error occurs when adding the first load. If you need to perform any further tests, you can formulate the problem, and we will conduct them.

**Comment by TonyXiang8787** [comment]
Hi @WinApiMan,

Do all the 166 transformers have `Yyn` connection **without** internal delta-winding? What are the `i0` (no-load current in p.u.) values of those transformers? How asymmetric is your loads behind the transformer? 

The main problem is the limited flow path of zero sequence current. After the fix in #1197, we allow the zero sequence current at `yn` side of `Yyn` to flow into the ground through the magnetization impedance.  So it allows some zero-sequence current flowing (as opposed to current `main`). But the ability is limited. If the `asym_load` behind the transformer has significant power difference between the phases, the calculation will not succeed.

This is also representing real-world. A `Yyn` transformer **without** internal delta-winding can only allow slightly asymmetric loads behind the transformer.

**Comment by WinApiMan** [comment]
Hi @TonyXiang8787! Data from analysis. 166 transformers where divided into 4 subnetworks, unrelated to each other. A single symmetrical load (calculate_model_the load is connected.json) was added to a network of 63 transformers with a capacity of 25 to 400 kVA (YYn). The transformer Io ranged from 1.5 to 4%. But it's interesting, that the error also occurs when the load is disconnected (calculate_model_the load is disconnected.json). 

Regarding your idea about the power difference between the phases of an asymmetric load, we believe you're right. And the difference between the phases can be about 2-3%. We can do this check on our side and perhaps you should also add the same check when validating asymmetric load.

[calculate_model_the load is disconnected.json](https://github.com/user-attachments/files/23707326/calculate_model_the.load.is.disconnected.json)

[calculate_model_the load is connected.json](https://github.com/user-attachments/files/23707331/calculate_model_the.load.is.connected.json)

**Comment by TonyXiang8787** [comment]
Hi @WinApiMan,

By looking at your data, there are some links which are connecting two nodes with different rated voltage. Are you sure this is the intention?

**Comment by WinApiMan** [comment]
@TonyXiang8787 Could you please be more specific and send me the Id's of at least a couple of lines?

**Comment by TonyXiang8787** [comment]
> [@TonyXiang8787](https://github.com/TonyXiang8787) Could you please be more specific and send me the Id's of at least a couple of lines?

@WinApiMan the link `89800` is connecting to node `85047` which has rated voltage of `10kV` and node `89799` which has rated voltage of `400V`.

**Comment by WinApiMan** [comment]
@TonyXiang8787 Thank you, you're right, it shouldn't be like this, we'll look into it.

**Comment by WinApiMan** [comment]
@TonyXiang8787 We fixed our local error (the substation diagram was drawn incorrectly). We also added validation to prevent such cases. Here is the corrected file, unfortunately with a sparse matrix error.

[calculate_model.json](https://github.com/user-attachments/files/23722540/calculate_model.json)

**Comment by WinApiMan** [comment]
Hi @TonyXiang8787! For testing purposes, we also generated a model without LINK connections and replaced them with LINE connections. The sparse matrix error remained.

[calculate_model_link to line.json](https://github.com/user-attachments/files/23741610/calculate_model_link.to.line.json)

**Comment by TonyXiang8787** [comment]
> Hi [@TonyXiang8787](https://github.com/TonyXiang8787)! For testing purposes, we also generated a model without LINK connections and replaced them with LINE connections. The sparse matrix error remained.
> 
> [calculate_model_link to line.json](https://github.com/user-attachments/files/23741610/calculate_model_link.to.line.json)

Hi @WinApiMan,

As I indicated, the `Yyn` transformer only allows very limited unbalanced load behind the transformer. In your data, your `asym_load` is still too unbalanced:

```json
      {
        "id": 49386,
        "node": 46160,
        "status": 1,
        "type": 0,
        "p_specified": [
          20000,
          20000,
          20000
        ],
        "q_specified": [
          17000,
          16000,
          15000
        ]
      }
```

If I change the `q_specified` to only small difference between the phases, the calculation succeeds.

```json
      {
        "id": 49386,
        "node": 46160,
        "status": 1,
        "type": 0,
        "p_specified": [
          20000,
          20000,
          20000
        ],
        "q_specified": [
          16200,
          16000,
          15800
        ]
      }
```

**Comment by WinApiMan** [comment]
@TonyXiang8787 Thanks for informing me.  Based on our operation experience, a 160 kVA  Y/Yn transformer can easily withstand a 2 kVA phase asymmetry.
("p_specified": [20000, 20000, 20000], "q_specified": [17000, 16000, 15000]). In fact, this happens quite often in 0,4kV networks. Perhaps it would be worthwhile to create some kind of description of the limitations on the use of asymmetric network calculation in the future.

For example, the load asymmetry coefficient by phase is like this, the number of transformers in one network is of such and such a type, the parameters of the source are like this, and so on.

Unfortunately, it turns out that we are currently adjusting the network to the calculation task, rather than calculating the calculation in a specific real network.

**Comment by TonyXiang8787** [comment]
Hi @WinApiMan, thank you again for your feedback. If 2kVA phase asymmetry is very common for 160 kVA Y/yn transformers, that means we still do not get our calculation correct. Our other users until now do not have this vector group, thus our experiences on modelling zero-sequence circuit of Y/yn transformers are limited.

Your practical insights provide valuable information for us to improve. I will dive more into the literature to see how we should model zero-sequence of Y/yn transformers properly. If you have any literatur to share, just let us know. To be continued!

**Comment by TonyXiang8787** [comment]
Hi @WinApiMan,

After some literature study I have found that we indeed missed one important aspect. When transformer is configured in core-type with 3 legs, which is quite usual for distribution transformers, the zero sequence magnetization impedance can be rather small because there is no flux path in the iron core. Typically that in the range of 70-140% of transformer per unit impedance.

To fix that, we need to define a new attribute. It can be called `i0_zero` which is similar for `i0` but for zero sequence. It can also be called `mag0_ratio`, which is the ratio between zero sequence magnetization impedance and positive sequence short circuit impedance. There are also other ways to define this.

I am wondering what kind of attribute you can get from the transformer specification? If would be nice if you can provide us a transformer specsheet with the zero sequence parameters, so we can think about which attribute to define is making more sense.

**Comment by WinApiMan** [comment]
Hi @TonyXiang8787! We'll send you a database of transformers used in distribution networks, along with their specifications. However, in the future, you may want to consider switching to calculating asymmetric modes using the symmetric components method.

[PowerTransformers.xlsx](https://github.com/user-attachments/files/23769059/PowerTransformers.xlsx)

VoltageClassHighId this is our field, you don't need it, I forgot to delete it :)

**Comment by WinApiMan** [comment]
> ur practical insights provide valuable information for us to improve. I will dive more into the literature to see how we should model zero-sequence of Y/yn transformers properly. If you have any literatur to share, just let us know. To be continued!

Hi @TonyXiang8787! Regarding our literature. In your documentation, the π-shaped equivalent circuit contains conductivity Y. In the classical equivalent circuit, there are two of them, Y1 and Y2.

https://power-grid-model.readthedocs.io/en/stable/user_manual/components.html#id8

[π-shaped equivalent.docx](https://github.com/user-attachments/files/23819640/-shaped.equivalent.docx)

**Comment by TonyXiang8787** [comment]
Hi @WinApiMan,

After some literature study I think we found the problem and the possible solution. As I said before, in current `main` we always assume that the magnetization current/impedance is the same for positive and zero sequence. This is not true for 3-leg core-type transformers, which are the standard core configuration for distribution transformers. That's why you see limited capability to handle zero-sequence current and thus unbalanced loads.

To fix this problem, we have added two new attributes to let user specify zero sequence magnetization current/loss.

To test your case, please do the following:

  1. Rebuild PGM with the latest head in #1197.
  2. In your input data preparation, add one additional attribute `i0_zero_sequence` to the transformers with 3-leg core-type (bascially all the MV/LV transformer). You can use the value from transformer specification. If that's not available, a good guess is `i0_zero_sequence = 1.0`.
  3. Retry power flow.

**Comment by WinApiMan** [comment]
@TonyXiang8787 , Thank you!We will test it and get back to you with the results.

**Comment by WinApiMan** [comment]
Hi @TonyXiang8787! We did calculation using new pgm version. Used network that contains 16 transformers and had 7 asymmetric and some symmetric loads. In some loads. The asymmetric coefficient was increased to 100% on some transformers. All tests were successfully completed and the model was calculated. We'll continue testing with larger models. If we discover a bug, we'll let you know. Thanks for your help!
